### ISSUE TITLE
Team formation

### ISSUE THREAD

**Issue by immavalls** [kcdspain/barcelona-2024#1]
## What

Since this is a co-located event, we want to fill the following roles in the [KCD Barcelona 2024 organization](https://github.com/cncf/kubernetes-community-days/issues/530): program committee, marketing, support, and event coordination.

Since this is a co-located event, many aspects of an in-person conference (venue, sponsors, venue, catering, speakers communications, etc.) are solved by the event host https://www.devbcn.com/.

:heavy_exclamation_mark: We don't know at this time how many people from KCD can join the event free of charge. So far we think it will be 6 people, and if we are more than 6 we'll see.

## How

[KCDs](https://www.cncf.io/kcds/) are organized following the template at https://github.com/cncf/kubernetes-community-days.

The checklist:[Kubernetes Community Days Conference Action Items and Assignments](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170).  Since this is a co-located event, we'll have a shorter list of tasks depending on our team.

#### Responsibilities

- Talk review and selection for the KCD track. The CFP is already open https://sessionize.com/devbcn-2024/
- Schedule the 2-day track.
- Coordinate with the DevBcn team for the final schedule and publication.

##### Time required

Call For Speakers closes mid-April. 

Work will be continuous (~2 hours per week). DevBcn does not wait until the end to choose the talks. They keep reviewing periodically and they publish accepted speakers during the CFS period. At the closing (mid-April), we might have a bit more work to help build the final schedule and choose a few talks if we are still not finished accepting them all.

#### Responsibilities

- Website.
- Social media / Community management. 
- Coordinate communications with the DevBcn team.

##### Time required

~6 hours each week, pretty consistent work: early stages to start talking about the event, mid-term to raise awareness for the call for papers, near the event date to publicity the event and the talks, during the event to create momentum in the social networks.

#### Responsibilities

- Manage the KCD track during the event (control room entry, present speakers).
- Be at the KCD Spain/Cloud Native Barcelona booth (sponsors area) at the event.

##### Time required

June 13th and 14th, this team will be at the event. 

#### Responsibilities

- Project management.
- CNCF interactions.
- Coordination with DevBcn.

##### Time required

We estimate ~3-4 hours each week, with some extra work during the early stages.

## Team

| Role               | Members | Notes |
| ------------------ | ------ | ----- |
| Event coordination |  @raelga  @immavalls  |   |
| Program Committee  | @pablochacin  @chrsalx @acarmona @joseadanof @MrsDaehin @daverick  @raelga @immavalls  |   |
| Marketing  | @pablochacin @joseadanof |   |
| Support |  @chrsalx @joseadanof @immavalls |   |

**Comment by pablochacin** [comment]
Interested in be part of the Program Committee.

As there seems no to be much work until the CfP closes, can also help with other activities (coordination, marketing)

**Comment by chrsalx** [comment]
Hi! I'm interested in being part of of the committee. I can help with anything, really.

If I had to pick it will be either marketing or support.

**Comment by joseadanof** [comment]
Hi everyone! I'm interested in being part of the Program Committee.
I can offer my availability to work in Marketing or Support.

**Comment by MrsDaehin** [comment]
I am up for helping out with the comittee :) And anything else needed ofc.

**Comment by daverick** [comment]
Hi, I would be happy to bring my help in the Program Committee.

**Comment by immavalls** [comment]
Closing this issue as we have formed the team 🎉
